name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # Docker Hub registry base name
  REGISTRY_BASENAME: manishrana12
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  #IMAGE_NAME: `basename ${{ github.repository }}` # Resulted in workflow failure

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker-compose build --no-cache --force-rm

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test the Docker image
        run: docker-compose up -d

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set the base repository name without the Owner
        id: repo-basename
        run: |
          #echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
          echo "REPO_NAME_FOR_IMAGE_NAME=`basename ${{ github.repository }}`" >> "$GITHUB_ENV"
          #shell: bash # Resulted in error

      - name: Get the base repository name
        id: print-repo-basename
        run: |
          echo "${{ env.REPO_NAME_FOR_IMAGE_NAME }}" # This will output "repository name"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        #if: github.event_name != 'pull_request' # Conditional login to Docker Hub
        #uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker (Docker meta)
        id: meta
        #uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        uses: docker/metadata-action@v4
        with:
          #images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          #images: ${{ env.REGISTRY }}/${{ env.REGISTRY_BASENAME }}/${{ env.REPO_NAME_FOR_IMAGE_NAME }} # works
          #images: ${{ env.REGISTRY }}/${{ steps.repo-basename.outputs.value}}
          images: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_BASENAME }}/${{ env.REPO_NAME_FOR_IMAGE_NAME }}
          tags: |
            #type=ref,event=branch  
            #type=ref,event=pr
            #type=semver,pattern={{version}}
            #type=semver,pattern={{major}}.{{minor}}
            #type=sha
            # dynamically set the branch name as a prefix
            type=sha,prefix={{branch}}-
            # dynamically set the branch name and sha as a custom tag
            #type=raw,value=mytag-{{branch}}-{{sha}}

      - name: Build and push Docker image
        id: build-and-push
        #uses: docker/build-push-action@v2
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:src"
          #context: "{{defaultContext}}:daisyui-vue-client"
          #push: ${{ github.event_name != 'pull_request' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
        